import { DimensionDef, StockData } from './types';

export const DIMENSIONS: DimensionDef[] = [
  {
    id: 'profitability',
    title: '第一维度：盈利能力的“含金量”',
    description: '回答核心问题：这门生意本身好不好做？',
    indicators: [
      {
        key: 'grossMargin',
        title: '1. 毛利率 (Gross Margin)',
        subtitle: '分析关键点：行业地位的“护城河”。',
        description: '这四家公司谁的毛利高，说明谁做的零部件更难产，或者谁在苹果面前更有定价权。',
        warning: '警惕：如果毛利率连续下跌，往往是行业内卷（价格战）或大客户压价的直接信号。',
        unit: '%',
        higherIsBetter: true,
      },
      {
        key: 'netProfitMargin',
        title: '2. 净利率 (Net Profit Margin)',
        subtitle: '分析关键点：管理层的“抠门”程度（控费能力）。',
        description: '制造业利润薄如刀片。毛利高不代表赚钱，如果三费（销售、管理、财务费用）失控，净利就会很难看。',
        warning: '对比：谁的净利率最稳定，谁的管理体系就最成熟。',
        unit: '%',
        higherIsBetter: true,
      },
      {
        key: 'roe',
        title: '3. 净资产收益率 (ROE)',
        subtitle: '分析关键点：股东资金的使用效率 (指标之王)。',
        description: '这是巴菲特最看重的指标。它综合反映了公司加杠杆的能力、周转的速度和产品的利润。',
        warning: '标准：长期维持在 15%-20% 以上的公司通常是非常优秀的。',
        unit: '%',
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'efficiency',
    title: '第二维度：营运效率的“生死时速”',
    description: '电子产品贬值极快，回答：公司的反应速度够不够快？',
    indicators: [
      {
        key: 'inventoryDays',
        title: '4. 存货周转天数 (Inventory Turnover Days)',
        subtitle: '分析关键点：货是“金子”还是“垃圾”。',
        description: '越短越好。手机行业三个月就是一代。如果库存积压超过90天甚至半年，这些库存大概率要计提减值。',
        warning: '对比：既然都做果链，谁的天数短，谁的供应链管理就更牛。',
        unit: '天',
        higherIsBetter: false,
      },
      {
        key: 'arDays',
        title: '5. 应收账款周转天数 (DSO)',
        subtitle: '分析关键点：对大客户的“卑微”程度。',
        description: '反映了：货卖出去了，多久能把钱收回来？',
        warning: '风险：如果天数激增，说明客户拖欠货款，现金流会非常紧张，甚至有坏账风险。',
        unit: '天',
        higherIsBetter: false,
      },
      {
        key: 'fixedAssetTurnover',
        title: '6. 固定资产周转率 (FAT)',
        subtitle: '分析关键点：机器是不是在“空转”。',
        description: '这个指标越高，说明每一块钱的设备产出的收入越高。',
        warning: '警惕：如果公司疯狂扩产，但这个指标在下降，说明产能过剩了。',
        unit: '次',
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'safety',
    title: '第三维度：真金白银的“安全垫”',
    description: '回答：赚的是真钱还是假钱？能不能活下去？',
    indicators: [
      {
        key: 'netCashToProfit',
        title: '7. 净现比 (Operating Cash Flow / Net Profit)',
        subtitle: '分析关键点：利润的“含水量”。',
        description: '经营活动现金净流量 ÷ 净利润。这意味着每赚1块钱利润，有多少现金流进账。',
        warning: '标准：最好 > 1。如果长期 < 1，说明赚的钱都变成了厂房、机器或别人的欠条。',
        unit: 'x',
        higherIsBetter: true,
      },
      {
        key: 'quickRatio',
        title: '8. 速动比率 (Quick Ratio)',
        subtitle: '分析关键点：突发危机时的“救命钱”。',
        description: '速动比率剔除了存货，只看现金和能立马变现的资产够不够还短期债。',
        warning: '标准：最好 > 1。低于1说明短期偿债压力大。',
        unit: 'x',
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'growth',
    title: '第四维度：未来增长的“引擎”',
    description: '回答：这公司还有没有未来？',
    indicators: [
      {
        key: 'rdRatio',
        title: '9. 研发费用率 (R&D Ratio)',
        subtitle: '分析关键点：从“代工”转“研发”的决心。',
        description: '消费电子这行，不进则退。',
        warning: '对比：谁的研发投入占比高，谁在下一个风口活下来的概率就大。',
        unit: '%',
        higherIsBetter: true,
      },
      {
        key: 'cagr',
        title: '10. 营收复合增长率 (CAGR - 3yr)',
        subtitle: '分析关键点：穿越周期的成长性。',
        description: '不要只看某一年的爆发，要看过去3年的平均增速。',
        warning: '对比：谁能在大环境不好的情况下依然保持双位数增长，谁就在抢占市场份额。',
        unit: '%',
        higherIsBetter: true,
      },
    ],
  },
];

// Updated Mock Data for 2022, 2023, 2024
export const MOCK_STOCKS: StockData[] = [
  {
    id: 'luxshare',
    code: '002475',
    name: '立讯精密 (Luxshare)',
    exchange: 'SZSE',
    color: '#3b82f6', // blue
    data: {
      grossMargin: [{ year: '2022', value: 12.19 }, { year: '2023', value: 11.58 }, { year: '2024', value: 12.05 }],
      netProfitMargin: [{ year: '2022', value: 4.9 }, { year: '2023', value: 4.8 }, { year: '2024', value: 5.1 }],
      roe: [{ year: '2022', value: 20.8 }, { year: '2023', value: 19.2 }, { year: '2024', value: 18.5 }],
      inventoryDays: [{ year: '2022', value: 52 }, { year: '2023', value: 50 }, { year: '2024', value: 48 }],
      arDays: [{ year: '2022', value: 78 }, { year: '2023', value: 82 }, { year: '2024', value: 85 }],
      fixedAssetTurnover: [{ year: '2022', value: 6.5 }, { year: '2023', value: 6.8 }, { year: '2024', value: 7.0 }],
      netCashToProfit: [{ year: '2022', value: 1.25 }, { year: '2023', value: 1.3 }, { year: '2024', value: 1.4 }],
      quickRatio: [{ year: '2022', value: 0.98 }, { year: '2023', value: 1.05 }, { year: '2024', value: 1.02 }],
      rdRatio: [{ year: '2022', value: 4.5 }, { year: '2023', value: 4.2 }, { year: '2024', value: 4.6 }],
      cagr: [{ year: '2022', value: 30 }, { year: '2023', value: 18 }, { year: '2024', value: 15 }],
    },
  },
  {
    id: 'goertek',
    code: '002241',
    name: '歌尔股份 (Goertek)',
    exchange: 'SZSE',
    color: '#ef4444', // red
    data: {
      grossMargin: [{ year: '2022', value: 11.1 }, { year: '2023', value: 9.2 }, { year: '2024', value: 10.5 }],
      netProfitMargin: [{ year: '2022', value: 1.7 }, { year: '2023', value: 1.1 }, { year: '2024', value: 2.3 }],
      roe: [{ year: '2022', value: 5.8 }, { year: '2023', value: 3.2 }, { year: '2024', value: 6.5 }],
      inventoryDays: [{ year: '2022', value: 75 }, { year: '2023', value: 80 }, { year: '2024', value: 72 }],
      arDays: [{ year: '2022', value: 70 }, { year: '2023', value: 72 }, { year: '2024', value: 68 }],
      fixedAssetTurnover: [{ year: '2022', value: 3.1 }, { year: '2023', value: 2.8 }, { year: '2024', value: 3.0 }],
      netCashToProfit: [{ year: '2022', value: 4.5 }, { year: '2023', value: 4.8 }, { year: '2024', value: 3.5 }], 
      quickRatio: [{ year: '2022', value: 0.75 }, { year: '2023', value: 0.78 }, { year: '2024', value: 0.85 }],
      rdRatio: [{ year: '2022', value: 5.0 }, { year: '2023', value: 4.8 }, { year: '2024', value: 5.1 }],
      cagr: [{ year: '2022', value: 15 }, { year: '2023', value: -5 }, { year: '2024', value: 8 }],
    },
  },
  {
    id: 'lens',
    code: '300433',
    name: '蓝思科技 (Lens)',
    exchange: 'SZSE',
    color: '#10b981', // green
    data: {
      grossMargin: [{ year: '2022', value: 19.2 }, { year: '2023', value: 21.8 }, { year: '2024', value: 22.5 }],
      netProfitMargin: [{ year: '2022', value: 5.2 }, { year: '2023', value: 6.8 }, { year: '2024', value: 7.5 }],
      roe: [{ year: '2022', value: 7.8 }, { year: '2023', value: 10.5 }, { year: '2024', value: 11.2 }],
      inventoryDays: [{ year: '2022', value: 42 }, { year: '2023', value: 40 }, { year: '2024', value: 38 }],
      arDays: [{ year: '2022', value: 88 }, { year: '2023', value: 86 }, { year: '2024', value: 84 }],
      fixedAssetTurnover: [{ year: '2022', value: 1.3 }, { year: '2023', value: 1.4 }, { year: '2024', value: 1.45 }],
      netCashToProfit: [{ year: '2022', value: 2.2 }, { year: '2023', value: 1.8 }, { year: '2024', value: 1.9 }],
      quickRatio: [{ year: '2022', value: 1.2 }, { year: '2023', value: 1.3 }, { year: '2024', value: 1.4 }],
      rdRatio: [{ year: '2022', value: 5.1 }, { year: '2023', value: 5.5 }, { year: '2024', value: 5.8 }],
      cagr: [{ year: '2022', value: 15 }, { year: '2023', value: 12 }, { year: '2024', value: 10 }],
    },
  },
  {
    id: 'lingyi',
    code: '002600',
    name: '领益智造 (Lingyi)',
    exchange: 'SZSE',
    color: '#f59e0b', // amber
    data: {
      grossMargin: [{ year: '2022', value: 18.2 }, { year: '2023', value: 19.5 }, { year: '2024', value: 20.1 }],
      netProfitMargin: [{ year: '2022', value: 4.5 }, { year: '2023', value: 5.8 }, { year: '2024', value: 6.2 }],
      roe: [{ year: '2022', value: 9.5 }, { year: '2023', value: 11.2 }, { year: '2024', value: 12.0 }],
      inventoryDays: [{ year: '2022', value: 35 }, { year: '2023', value: 36 }, { year: '2024', value: 34 }],
      arDays: [{ year: '2022', value: 92 }, { year: '2023', value: 90 }, { year: '2024', value: 88 }],
      fixedAssetTurnover: [{ year: '2022', value: 3.0 }, { year: '2023', value: 3.2 }, { year: '2024', value: 3.4 }],
      netCashToProfit: [{ year: '2022', value: 1.6 }, { year: '2023', value: 1.4 }, { year: '2024', value: 1.5 }],
      quickRatio: [{ year: '2022', value: 0.9 }, { year: '2023', value: 0.92 }, { year: '2024', value: 0.95 }],
      rdRatio: [{ year: '2022', value: 3.8 }, { year: '2023', value: 4.0 }, { year: '2024', value: 4.2 }],
      cagr: [{ year: '2022', value: 18 }, { year: '2023', value: 10 }, { year: '2024', value: 12 }],
    },
  },
];